### ISSUE TITLE
[BUG] Stylizer is not disabling prefix.

### ISSUE THREAD

**Issue by SirCraftypants** [OmegaWeaponDev/Stylizer-Issues#1]
Stylizer is not disabling prefixes in Display Name

Also, only my opped account actually had the prefix in the display name.

MC 1.17.1
java 16
paper 1.17.1 #151
Stylizer 2.0.24

**Comment by SirCraftypants** [comment]
I made sure that Essentials prefix display name was disabled, also made sure it was disabled in my chat plugin and my custom items plugin. 

I then decided to remove stylizer from the server and it fixed the issue by removing the prefix from my display name.

**Comment by SirCraftypants** [comment]
I just realized, it's supposed to be putting the prefix in a tablist right, well i have the tablist disabled and its putting the prefix in my display name. 
![2021-08-03](https://user-images.githubusercontent.com/66942713/128069556-22b122a5-6f4c-41da-be39-ec0ce39d7fae.png)

**Comment by SirCraftypants** [comment]
they only way i can get rid of the prefix in my display name is by removing stylizer from my server

**Comment by OmegaWeaponDev** [comment]
Hi,

Firstly, Next time please follow the issue templates that have been setup.

I will add an option when I have some time to disable the prefix in the above head names.

**Comment by SirCraftypants** [comment]
Thank you for adding it, my reason for not sticking to the template was because i wasted almost an entire day trying to find what was causing it, when i first installed Stylizer is was just a chat styling plugin so i had no idea it was causing it so was over looking it. So i was extreme annoyed and frustrated and it pretty much turned my day on it's head. I understand that wasn't your fault, i should have paid more attention to stylizers evolution but i wasn't expecting it to evolve the way it has.
